Repository sm-adil/portfolio, pull requests merged in 2020-08, with the labels that each got.

#15 feat(commitizen): make repo commitizen friendly 🤗
  README.md
  package-lock.json
  package.json
Labels: feature

#16 feat(netlify-badge): add netlify status badge
  README.md
Labels: feature

#17 feat(release-drafter): add release-drafter to the repo 🌟
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: feature

#18 feat(images): add responsive project images
  public/images/projects/glugpace.jpg
  public/images/projects/glugpace/glugpace__1071.jpg
  public/images/projects/glugpace/glugpace__1272.jpg
  public/images/projects/glugpace/glugpace__1400.jpg
  public/images/projects/glugpace/glugpace__200.jpg
  public/images/projects/glugpace/glugpace__583.jpg
  public/images/projects/glugpace/glugpace__850.jpg
  public/images/projects/trawell.jpg
  public/images/projects/trawell/trawell__1015.jpg
  public/images/projects/trawell/trawell__1206.jpg
  public/images/projects/trawell/trawell__1394.jpg
  public/images/projects/trawell/trawell__1400.jpg
  public/images/projects/trawell/trawell__200.jpg
  public/images/projects/trawell/trawell__550.jpg
  public/images/projects/trawell/trawell__799.jpg
  public/images/projects/tutor.jpg
  public/images/projects/tutor/tutor__1113.jpg
  public/images/projects/tutor/tutor__1223.jpg
  public/images/projects/tutor/tutor__1330.jpg
  public/images/projects/tutor/tutor__1398.jpg
  public/images/projects/tutor/tutor__1400.jpg
  public/images/projects/tutor/tutor__200.jpg
  public/images/projects/tutor/tutor__383.jpg
  public/images/projects/tutor/tutor__531.jpg
  public/images/projects/tutor/tutor__650.jpg
  public/images/projects/tutor/tutor__767.jpg
  public/images/projects/tutor/tutor__884.jpg
  public/images/projects/tutor/tutor__989.jpg
  src/components/projects.tsx
  src/projects-data.json
Labels: feature

#20 refactor(release): add dependency label on release drafter
  .github/release-drafter.yml
Labels: refactor

#21 fix(release-drafter): add configuration path to release-drafter workflow
  .github/workflows/release-drafter.yml
Labels: fix

#22 fix(release-drafter): use config-name instead of configuration-path
  .github/workflows/release-drafter.yml
Labels: fix

#23 chore/add postversion script
  package.json
Labels: chore

#24 refactor(package.json): update postversion script
  package.json
Labels: refactor

#25 refactor(postversion): remove postversion script
  package.json
Labels: refactor

#29 feat(service-worker): add service worker
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/apple-touch-icon.png
  public/browserconfig.xml
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/index.html
  public/manifest.json
  public/mstile-150x150.png
  public/safari-pinned-tab.svg
  src/index.tsx
  src/serviceWorker.js
Labels: feature

#30 refactor(footer): update social links
  src/components/footer.tsx
Labels: refactor

#31 fix(projects-data): fix broken project links
  src/projects-data.json
Labels: fix

#32 fix: typos ✍
  src/projects-data.json
Labels: fix

#39 chore(release-drafter): update name and tag template for release drafter
  .github/release-drafter.yml
Labels: refactor
